-- OpenCode provider: plugin installer for ~/.config/opencode/plugins

local M = {}

local utils = require 'nvim-claude.utils'

local function plugin_root()
  local src = debug.getinfo(1, 'S').source:sub(2)
  local root = src:match('(.*/)lua/nvim%-claude/')
  if root then
    if root:sub(-1) ~= '/' then
      root = root .. '/'
    end
    return root
  end
  local fallback = vim.fn.fnamemodify(src, ':h:h:h:h') .. '/'
  if fallback:sub(-1) ~= '/' then
    fallback = fallback .. '/'
  end
  return fallback
end

local function opencode_config_root()
  local xdg = vim.env.XDG_CONFIG_HOME
  if xdg and xdg ~= '' then
    return xdg .. '/opencode'
  end
  return vim.fn.expand('~/.config/opencode')
end

local function ensure_plugin_dir()
  local plugin_dir = opencode_config_root() .. '/plugins'
  if vim.fn.isdirectory(plugin_dir) == 0 then
    local ok = vim.fn.mkdir(plugin_dir, 'p')
    if ok ~= 1 then
      return nil, 'Failed to create OpenCode global plugins directory'
    end
  end
  return plugin_dir
end

local function global_plugin_file()
  return opencode_config_root() .. '/plugins/nvim-claude.js'
end

local function stale_plugin_files()
  local files = {
    opencode_config_root() .. '/plugin/nvim-claude.js',
  }

  local project_root = utils.get_project_root()
  if project_root and project_root ~= '' then
    table.insert(files, project_root .. '/.opencode/plugins/nvim-claude.js')
    table.insert(files, project_root .. '/.opencode/plugin/nvim-claude.js')
  end

  return files
end

local function remove_plugin_files(files)
  for _, plugin_file in ipairs(files) do
    if utils.file_exists(plugin_file) then
      local ok = pcall(vim.fn.delete, plugin_file)
      if not ok then
        return false, plugin_file
      end
    end
  end
  return true
end

local function remove_path(path, flags)
  if not utils.file_exists(path) then
    return true
  end
  local ok
  if flags and flags ~= '' then
    ok = pcall(vim.fn.delete, path, flags)
  else
    ok = pcall(vim.fn.delete, path)
  end
  if not ok then
    return false, path
  end
  return true
end

local function remove_empty_dir(path)
  if vim.fn.isdirectory(path) == 0 then
    return true
  end
  if #vim.fn.readdir(path) > 0 then
    return true
  end
  return remove_path(path, 'd')
end

local function should_remove_project_bootstrap(package_path)
  local pkg = utils.read_json(package_path)
  if type(pkg) ~= 'table' then
    return false
  end

  local deps = pkg.dependencies
  if type(deps) ~= 'table' then
    return false
  end

  local dep_count = 0
  for dep_name, dep_value in pairs(deps) do
    dep_count = dep_count + 1
    if dep_name ~= '@opencode-ai/plugin' or type(dep_value) ~= 'string' then
      return false
    end
  end

  if dep_count ~= 1 then
    return false
  end

  for key, _ in pairs(pkg) do
    if key ~= 'dependencies' then
      return false
    end
  end

  return true
end

local function cleanup_project_bootstrap()
  local project_root = utils.get_project_root()
  if not project_root or project_root == '' then
    return true
  end

  local opencode_root = project_root .. '/.opencode'
  local package_path = opencode_root .. '/package.json'
  if not should_remove_project_bootstrap(package_path) then
    return true
  end

  local paths = {
    package_path,
    opencode_root .. '/package-lock.json',
    opencode_root .. '/bun.lock',
    opencode_root .. '/.gitignore',
  }

  for _, path in ipairs(paths) do
    local ok, failed_path = remove_path(path)
    if not ok then
      return false, failed_path
    end
  end

  local ok, failed_path = remove_path(opencode_root .. '/node_modules', 'rf')
  if not ok then
    return false, failed_path
  end

  for _, path in ipairs({
    opencode_root .. '/plugin',
    opencode_root .. '/plugins',
    opencode_root,
  }) do
    local dir_ok, dir_failed_path = remove_empty_dir(path)
    if not dir_ok then
      return false, dir_failed_path
    end
  end

  return true
end

local function escape_js_single_quotes(value)
  return value:gsub('\\', '\\\\'):gsub("'", "\\'"):gsub('%%', '%%%%')
end

local function plugin_template(root)
  local root_escaped = escape_js_single_quotes(root)
  local template = [[
// Generated by nvim-claude (OpenCode provider)
import path from 'path'
import { Buffer } from 'buffer'

const pluginRoot = '__PLUGIN_ROOT__'
const rpcPath = path.join(pluginRoot, 'rpc', 'nvim-rpc.sh')

const toBase64 = (value) => {
  if (value === undefined || value === null) return ''
  return Buffer.from(String(value), 'utf8').toString('base64')
}

const normalizePath = (baseDir, filePath) => {
  if (!filePath || typeof filePath !== 'string') return null
  const trimmed = filePath.trim()
  if (!trimmed) return null
  if (path.isAbsolute(trimmed)) return path.normalize(trimmed)
  return path.resolve(baseDir, trimmed)
}

const getArgValue = (args, keys) => {
  if (!args || typeof args !== 'object') return null
  for (const key of keys) {
    const value = args[key]
    if (typeof value === 'string' && value.trim() !== '') return value
  }
  return null
}

const extractFilePath = (args) => getArgValue(args, ['file_path', 'filePath', 'path', 'file'])
const extractPatchText = (args) => getArgValue(args, ['patch_text', 'patchText', 'patch'])

const normalizeMetadata = (metadata) => {
  if (!metadata) return null
  if (typeof metadata === 'string') {
    try {
      return JSON.parse(metadata)
    } catch (error) {
      return null
    }
  }
  if (typeof metadata === 'object') return metadata
  return null
}

const extractPatchPaths = (baseDir, patchText) => {
  if (!patchText || typeof patchText !== 'string') return []
  const results = new Set()
  const lines = patchText.split(/\r?\n/)
  for (const line of lines) {
    const match = line.match(/^\*\*\* (?:Update|Add|Delete) File:\s*(.+)$/)
    if (!match) continue
    const filePath = normalizePath(baseDir, match[1])
    if (filePath) results.add(filePath)
  }
  return Array.from(results)
}

const extractChangedFiles = (baseDir, metadata) => {
  const meta = normalizeMetadata(metadata)
  if (!meta) return []
  const results = new Set()

  const addPath = (filePath) => {
    const normalized = normalizePath(baseDir, filePath)
    if (normalized) results.add(normalized)
  }

  const addFileEntry = (file) => {
    if (typeof file === 'string') {
      addPath(file)
      return
    }
    if (!file || typeof file !== 'object') return
    addPath(file.filePath || file.filepath || file.relativePath || file.path || file.file)
    addPath(file.movePath || file.move_path)
  }

  const files = meta.files || meta.files_changed || meta.filesChanged
  if (Array.isArray(files)) {
    for (const file of files) addFileEntry(file)
  }

  addPath(meta.filepath || meta.filePath)

  if (meta.filediff && typeof meta.filediff === 'object') {
    addPath(meta.filediff.file || meta.filediff.filePath || meta.filediff.path)
  }

  return Array.from(results)
}

const normalizeTool = (tool) => (typeof tool === 'string' ? tool.trim().toLowerCase() : '')

const isBashTool = (tool) => {
  const t = normalizeTool(tool)
  return t === 'bash' || t === 'shell'
}

const hasWriteLikeArgs = (args) => {
  if (!args || typeof args !== 'object') return false
  const filePath = extractFilePath(args)
  if (!filePath) return false
  return Boolean(
    extractPatchText(args)
    || Array.isArray(args.edits)
    || typeof args.content === 'string'
    || typeof args.text === 'string'
    || typeof args.old_string === 'string'
    || typeof args.new_string === 'string'
    || typeof args.oldString === 'string'
    || typeof args.newString === 'string'
    || typeof args.insert_text === 'string'
    || typeof args.insertText === 'string'
  )
}

const shouldTrackMutation = (tool, args) => {
  const t = normalizeTool(tool)
  if (isBashTool(t)) return false
  if (t === 'edit' || t === 'write' || t === 'patch' || t === 'apply_patch' || t === 'multiedit' || t === 'multi_edit') {
    return true
  }
  if (extractPatchText(args)) return true
  if (hasWriteLikeArgs(args)) return true
  return false
}

const collectTargets = (baseDir, args, metadata) => {
  const targets = new Set()
  const filePath = normalizePath(baseDir, extractFilePath(args))
  if (filePath) targets.add(filePath)
  const patchText = extractPatchText(args)
  if (patchText) {
    for (const pathItem of extractPatchPaths(baseDir, patchText)) {
      targets.add(pathItem)
    }
  }
  if (metadata) {
    for (const pathItem of extractChangedFiles(baseDir, metadata)) {
      targets.add(pathItem)
    }
  }
  return Array.from(targets)
}

const isRmCommand = (command) => typeof command === 'string' && /^\s*rm\b/.test(command)

const buildLsCommand = (command) => command.replace(/^\s*rm\b/, 'ls -d')

const resolveRmTargets = async (baseDir, command, $) => {
  if (!isRmCommand(command)) return []
  const lsCommand = buildLsCommand(command)
  if (!lsCommand) return []
  try {
    const output = await $.cwd(baseDir).nothrow()`${{ raw: lsCommand }}`.text()
    if (!output) return []
    return output
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line !== '' && !line.startsWith('ls:'))
      .map((line) => normalizePath(baseDir, line))
      .filter(Boolean)
  } catch (error) {
    return []
  }
}

const callAdapter = async ($, baseDir, targetFile, method, value) => {
  if (!method) return
  const payload = value === undefined || value === null || value === '' ? '' : toBase64(value)
  const expr = payload === ''
    ? `luaeval("require('nvim-claude.events.adapter').${method}()")`
    : `luaeval("require('nvim-claude.events.adapter').${method}('${payload}')")`
  const target = targetFile || baseDir
  try {
    // Use child_process.spawn directly to avoid any shell interpretation
    const { spawn } = await import('child_process')
    await new Promise((resolve) => {
      const proc = spawn(rpcPath, ['--remote-expr', expr], {
        env: { ...process.env, TARGET_FILE: target },
        stdio: 'ignore',
      })
      proc.on('close', resolve)
      proc.on('error', resolve)
    })
  } catch (error) {
    // Ignore RPC failures to avoid disrupting OpenCode
  }
}

export const NvimClaude = async ({ directory, worktree, $ }) => {
  const baseDir = path.resolve(directory || worktree || process.cwd())
  const pendingCalls = new Map()
  const seenMessages = new Set()

  return {
    'tool.execute.before': async (input, output) => {
      const callId = input && input.callID
      const tool = input && input.tool
      if (callId) {
        const storedArgs = (output && output.args) || (input && input.args) || null
        pendingCalls.set(callId, { tool: input.tool, args: storedArgs })
      }
      const args = (output && output.args) || (input && input.args) || {}
      if (shouldTrackMutation(tool, args)) {
        const targets = collectTargets(baseDir, args)
        for (const filePath of targets) {
          await callAdapter($, baseDir, filePath, 'pre_tool_use_b64', filePath)
        }
      }
      const command = args && args.command
      if (isBashTool(tool) && command) {
        const rmTargets = await resolveRmTargets(baseDir, command, $)
        for (const filePath of rmTargets) {
          await callAdapter($, baseDir, filePath, 'track_deleted_file_b64', filePath)
        }
      }
    },
    'tool.execute.after': async (input, output) => {
      const callId = input && input.callID
      const stored = callId ? pendingCalls.get(callId) : null
      if (callId) pendingCalls.delete(callId)
      const tool = (stored && stored.tool) || (input && input.tool)
      const args = (stored && stored.args) || (output && output.args) || (input && input.args) || {}
      if (shouldTrackMutation(tool, args)) {
        const targets = collectTargets(baseDir, args, output && output.metadata)
        for (const filePath of targets) {
          await callAdapter($, baseDir, filePath, 'post_tool_use_b64', filePath)
        }
      }
      const command = args && args.command
      if (isBashTool(tool) && command) {
        const remaining = await resolveRmTargets(baseDir, command, $)
        for (const filePath of remaining) {
          await callAdapter($, baseDir, filePath, 'untrack_failed_deletion_b64', filePath)
        }
      }
    },
    'chat.message': async (input, output) => {
      if (!output || !output.message) return
      const message = output.message
      if (!message || message.role !== 'user') return
      const messageId = message.id || (input && input.messageID)
      if (messageId && seenMessages.has(messageId)) return
      if (messageId) seenMessages.add(messageId)
      const parts = Array.isArray(output.parts) ? output.parts : []
      const text = parts
        .filter((part) => part && part.type === 'text' && typeof part.text === 'string')
        .map((part) => part.text)
        .join('')
      if (!text || text.trim() === '') return
      await callAdapter($, baseDir, baseDir, 'user_prompt_submit_b64', text)
    },
  }
}
]]

  return template:gsub('__PLUGIN_ROOT__', root_escaped)
end

function M.install()
  local plugin_dir, err = ensure_plugin_dir()
  if not plugin_dir then
    vim.notify('nvim-claude: ' .. (err or 'Failed to prepare OpenCode plugin'), vim.log.levels.ERROR)
    return false
  end
  local content = plugin_template(plugin_root())

  local plugin_file = global_plugin_file()
  local ok = utils.write_file(plugin_file, content)
  if not ok then
    vim.notify('nvim-claude: Failed to write OpenCode plugin', vim.log.levels.ERROR)
    return false
  end

  local removed_ok, removed_path = remove_plugin_files(stale_plugin_files())
  if not removed_ok then
    vim.notify('nvim-claude: Failed to remove old OpenCode plugin at ' .. removed_path, vim.log.levels.WARN)
  end

  local cleaned_ok, cleaned_path = cleanup_project_bootstrap()
  if not cleaned_ok then
    vim.notify('nvim-claude: Failed to clean old project .opencode state at ' .. cleaned_path, vim.log.levels.WARN)
  end

  vim.notify('nvim-claude: OpenCode plugin installed in ~/.config/opencode/plugins (restart OpenCode to reload plugins)', vim.log.levels.INFO)
  return true
end

function M.uninstall()
  local plugin_files = { global_plugin_file() }
  vim.list_extend(plugin_files, stale_plugin_files())
  local ok, failed_path = remove_plugin_files(plugin_files)
  if not ok then
    vim.notify('nvim-claude: Failed to remove OpenCode plugin at ' .. failed_path, vim.log.levels.ERROR)
    return false
  end

  local cleaned_ok, cleaned_path = cleanup_project_bootstrap()
  if not cleaned_ok then
    vim.notify('nvim-claude: Failed to clean old project .opencode state at ' .. cleaned_path, vim.log.levels.WARN)
  end

  vim.notify('nvim-claude: OpenCode plugin removed from global config (restart OpenCode to apply)', vim.log.levels.INFO)
  return true
end

return M
